### ISSUE TITLE
Lightning Wordpress Publisher and BTCPay -Fatal error: Uncaught Error: Class 'LightningChargeClient' not found

### ISSUE THREAD

**Issue by dbtcs1** [shesek/wordpress-lightning-paywall#6]
Hi, I have changed the setting from 'lnd' to 'clightning' to test out the LApps. I am on a LunaNode plan. Have enabled the Spark service.  Under Manage Store, have also completed the Test Connection and is ok and saved the changes.

Downloaded Lightning Publisher in Word Press and updated the Lightning Publisher settings (server url, public url and API token) and saved changes.

I received an error message when firing up the website (website is working when the Lightning Publisher is deactivated) : 

Fatal error: Uncaught Error: Class 'LightningChargeClient' not found in /home/domainname/public_html/wp-content/plugins/lightning-publisher/lightning-publisher.php:19 Stack trace: #0 /home/domainname/public_html/wp-content/plugins/lightning-publisher/lightning-publisher.php(195): Lightning_Publisher->__construct() #1 /home/domainname/public_html/wp-settings.php(322): include_once('/home/domainname/...') #2 /home/domainname/public_html/wp-config.php(90): require_once('/home/domainname/...') #3 /home/domainname/public_html/wp-load.php(37): require_once('/home/domainname/...') #4 /home/domainname/public_html/wp-blog-header.php(13): require_once('/home/domainname/...') #5 /home/domainname/public_html/index.php(17): require('/home/domainname/...') #6 {main} thrown in /home/domainname/public_html/wp-content/plugins/lightning-publisher/lightning-publisher.php on line 19.

Would appreciate help to resolve the issue. Thanks.

**Comment by shesek** [comment]
This seems quite odd, which version of PHP and WordPress are you using?

**Comment by dbtcs1** [comment]
PHP version 7.0, WordPress 4.9.9

**Comment by RangaMedia** [comment]
Tried the plugin on our WP site, and doesn't seem to work. the Pay Now button is there, but when you click on it it doesn't do anything.

**Comment by shesek** [comment]
@RangaMedia Are you able to otherwise access your lightning charge server, say using `curl`?
